baseURL = "https://emtincopa.github.io/"
languageCode = "en-us"
title = "EMT'S Data Stories"
copyright = "&copy; 2018 EMT'S Data stories"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^<sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_caches$"]
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true
publishDir = "../EMTincopa.github.io"


# Enable comments by entering your Disqus shortname
disqusShortname = "https-emtincopa-github-io"
# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-131186631-1"


[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/headataviz.jpg"
  SEOTitle = "My blog of Visualization and Storytelling with data."
  description = "El blog de un entusiasta de los datos | Storytelling and Data Visualization"
  keyword = "DataViz, El blog de EMTincopa, Storytelling with data, Data Visualization, Datos, VisualizaciÛn de datos, Data Stories"
  slogan = "La visualizaci√≥n de datos como medio expresivo para narrar lo que descubrimos."

  image_404 = "img/headupdating.gif"
  title_404 = "Te encuentras lejos de casa :("
  
  
  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""
  
  # algolia site search
  algolia_search = false 
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""
  
  
  # Sidebar settings
  sidebar_about_description = "Entusiasta de los datos, el DataViz, la Investigaci√≥n Operativa y de cada cosa que lo emociona."
  sidebar_avatar = "img/emt-profile.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2


  [params.social]
  rss           = true 
  #email        = "emtincopa@gmail.com"
  facebook      = "https://www.facebook.com/enrique.tincopa"
  twitter       = "https://twitter.com/EMTincopa"
  linkedin      = "https://www.linkedin.com/in/enrique-mendoza-tincopa-4b2a14173/"
  #instagram    = "https://www.instagram.com/emtincopa/"
  github        = "https://github.com/EMTincopa"
  
  bookmarks = true
  [[params.bookmark_link]]
  title =  "Flourish"
  href =  "https://flourish.studio/"
  [[params.bookmark_link]]
  title = "Quick-R"
  href =  "https://www.statmethods.net/"
  [[params.bookmark_link]]
  title = "Inzight"
  href = "https://www.stat.auckland.ac.nz/~wild/iNZight/"
  [[params.bookmark_link]]
  title =  "Visualization Analysis and Design - 1st Edition"
  href = "https://amzn.to/2GvfACm"
  [[params.bookmark_link]]
  title = "Dear Data"
  href = "https://amzn.to/2R4rdUR"
  [[params.bookmark_link]]
  title = "R for Data Science - 1st Edition"
  href = "https://amzn.to/2EBIFtX"


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
